# Generated by Django 4.2.1 on 2023-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='proyectos')),
                ('link', models.URLField(blank=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
