# Generated by Django 4.2.1 on 2023-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_alter_comentario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='certificados')),
                ('fecha_obtencion', models.DateTimeField(verbose_name='Fecha de obtención')),
            ],
        ),
    ]
