# Generated by Django 4.2.4 on 2023-08-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_alter_comentario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='link',
            new_name='link_repositorio',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link_web',
            field=models.URLField(blank=True),
        ),
    ]
